### PR TITLE
Missing letters for Kazakh (Arabic)

### PR DESCRIPTION
**Pull request by MuratKaribay**
Please add ڭ، ۇ، ۋ، ۆ. These letters are used in Kazakh. I added all variations of these 4 letters (isol, init, medi, fina)

### CODE REVIEW

**Comment by rastikerdar** [comment]
Thanks for adding these letters. Can you please give me a sample text or link (e.g. Wikipedia) so I can develop and test the font with it?

**Comment by MuratKaribay** [comment]
> Thanks for adding these letters. Can you please give me a sample text or link (e.g. Wikipedia) so I can develop and test the font with it?

Sorry do you need a screenshot with Vazir sample text or Kazakh (Arabic) writing style?

**Comment by rastikerdar** [comment]
Not a screenshot. I need some texts (e.g. web pages) in Kazakh (Arabic) for testing Vazir.

**Comment by MuratKaribay** [comment]
> Not a screenshot. I need some texts (e.g. web pages) in Kazakh (Arabic) for testing Vazir.

Like this? https://kk.wikipedia.org/w/index.php?title=%D0%98%D1%80%D0%B0%D0%BD&variant=kk-arab

**Comment by MuratKaribay** [comment]
@rastikerdar will you add these 4 letters?
If you give me permission I would like to use the Vazir font for Kazakh (Arabic) Wikipedia.
Do you have any plans to add all Arabic letters for all languages?

**Comment by rastikerdar** [comment]
Sure! I'm working on Vazir and I will merge your commit soon.

**Comment by rastikerdar** [comment]
How many more letters should we add for Arabic?

**Comment by MuratKaribay** [comment]
> How many more letters should we add for Arabic?

I think to start adding
Arabic
Arabic Presentation Form-A
Arabic Presentation Form-B

**Comment by MuratKaribay** [comment]
I'm thinking of adding letters to Vazir without Arabic ligatures.
If Arabic users need ligatures, then they will need a separate Vazir font, and for many languages they need a Persian style, for example, Kazakh and Uyghur, etc.

**Comment by MuratKaribay** [comment]
@rastikerdar many languages that have an Arabic script suffer from the lack of letters in the Vazir font for example in the screenshot Kazakh (Arabic)

image_2020-11-11_08-03-07

If you notice the letters ۇ ، ۋ ، ڭ in the screenshot only in the isolated view

**Comment by rastikerdar** [comment]
I see, Murat. You are right. I will try to release a new version soon.

**Pull request merged**
